name: Run Playwright Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup Playwright
        run: npm init playwright@latest

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx playwright test