name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx playwright test
